FROM quay.io/bcook/nubi:latest as builder

# install go
RUN dnf -y install golang

COPY hello.go .
COPY go.mod .

# build
RUN go build
RUN pwd

# copy binary to clean image
FROM registry.access.redhat.com/ubi9/ubi
COPY --from=builder /hello /usr/bin/hello
