[image-build]
kickstart = ubi-9.5-container.ks
target = guest-rhel-9.5.0-containers
ksversion = F26
format = docker
name = rhel-base-fs-container
arches = x86_64,s390x,aarch64,ppc64le
disk_size = 10
version = 9.5
ksurl = git+https://gitlab.cee.redhat.com/rhel/release-engineering/spin-kickstarts.git?rhel9#origin/rhel-9
distro = RHEL-9.5

[factory-parameters]
tar_options = --xattrs,--xattrs-exclude=security.selinux
